apiVersion: apps/v1
kind: Deployment
metadata:
  name: db-base
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      app: db
  template:
    metadata:
      labels:
        app: db
    spec:
      containers:
        - name: mysql
          image: acb23/fil_rouge-db
          env:
            - name: MYSQL_ROOT_PASSWORD
              value: root
            - name: MYSQL_DATABASE
              value: fil_rouge
            - name: DATABASE_USER
              value: root
            - name: DATABASE_HOST
              value: db
          ports:
            - containerPort: 3306
          resources:
            requests:
              memory: "512Mi"
              cpu: "500m"
            limits:
              memory: "1Gi"
              cpu: "1"
---
apiVersion: v1
kind: Service
metadata:
  name: db
  namespace: default
spec:
  selector:
    app: db
  ports:
    - protocol: TCP
      port: 3306
      targetPort: 3306
  type: NodePort
  nodePort: 31100
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: app-base
  namespace: default
spec:
  replicas: 2
  selector:
    matchLabels:
      app: app
  template:
    metadata:
      labels:
        app: app
    spec:
      containers:
        - name: php-apache
          image: acb23/fil_rouge-php
          ports:
            - containerPort: 80
          env:
            - name: DATABASE_HOST
              value: db
            - name: DATABASE_USER
              value: root
            - name: DATABASE_PASSWORD
              value: root
            - name: DATABASE_NAME
              value: fil_rouge
          resources:
            requests:
              memory: "256Mi"
              cpu: "250m"
            limits:
              memory: "512Mi"
              cpu: "500m"
      volumes:
        - name: app-volume
          emptyDir: {}
---
apiVersion: v1
kind: Service
metadata:
  name: app-service
  namespace: default
spec:
  selector:
    app: app
  ports:
    - name: http
      protocol: TCP
      port: 80
      targetPort: 80
  type: NodePort
  nodePort: 30100
